version: '3.8'

services:
  mysql:
    image: mysql:8.3
    container_name: world-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: world
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    restart: always