openapi: 3.0.3
info:
  title: World Country API
  version: 1.0.0
  description: Sample API based on World DB's country table

servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /countries:
    get:
      summary: Get all countries
      tags: [Country]
      responses:
        '200':
          description: List of countries
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Country'
    post:
      summary: Create a new country
      tags: [Country]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Country'
      responses:
        '201':
          description: Country created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Country'

  /countries/{code}:
    get:
      summary: Get country by code
      tags: [Country]
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
            example: USA
      responses:
        '200':
          description: Country found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Country'
        '404':
          description: Country not found
    put:
      summary: Update country by code
      tags: [Country]
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Country'
      responses:
        '200':
          description: Country updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Country'
    delete:
      summary: Delete country by code
      tags: [Country]
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Country deleted

components:
  schemas:
    Country:
      type: object
      required:
        - code
        - name
        - continent
        - region
        - surfaceArea
        - population
        - localName
        - governmentForm
        - code2
      properties:
        code:
          type: string
          example: USA
        name:
          type: string
          example: United States
        continent:
          type: string
          enum:
            - Asia
            - Europe
            - North America
            - Africa
            - Oceania
            - Antarctica
            - South America
        region:
          type: string
          example: North America
        surfaceArea:
          type: number
          format: float
          example: 9833517.0
        indepYear:
          type: integer
          nullable: true
          example: 1776
        population:
          type: integer
          example: 331002651
        lifeExpectancy:
          type: number
          format: float
          nullable: true
          example: 78.9
        gnp:
          type: number
          format: float
          nullable: true
          example: 21433225.0
        gnpOld:
          type: number
          format: float
          nullable: true
          example: 20611890.0
        localName:
          type: string
          example: United States
        governmentForm:
          type: string
          example: Federal Republic
        headOfState:
          type: string
          nullable: true
          example: Joe Biden
        capital:
          type: integer
          nullable: true
          example: 3813
        code2:
          type: string
          example: US
